version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-s3: circleci/aws-s3@2.0

workflows:
  s3 deployment: 
    jobs:
      - node/test:
          version: "15.1"
          post-steps:
            - run: npm run build
            - aws-s3/copy:
                from: dist/
                to: s3://sample-app-vue
                arguments: --recursive
